url: https://muellner.dev
author: Christoph Müllner
description: Homepage hosting personal information about myself
socials:
- name: Linkedin
  url: https://www.linkedin.com/in/christoph-muellner-at/
- name: Github
  url: https://github.com/chrismuellner
