siteTitle: Home
url: https://muellner.dev
author: Christoph Müllner
description: Homepage of Christoph Müllner
keywords: software engineer
socials:
- name: Linkedin
  url: https://www.linkedin.com/in/christoph-muellner-at/
- name: Github
  url: https://github.com/chrismuellner
